name: delivery_app
description: Multi-platform delivery management mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Forms and Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  
  # HTTP and API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Location and Maps
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Camera and Image Processing
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  image_compression: ^0.0.3
  
  # Signature Capture
  signature: ^5.4.0
  flutter_signature_pad: ^2.0.0
  
  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  
  # Real-time Communication
  socket_io_client: ^2.0.3+1
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.1
  
  # Charts and Data Visualization
  fl_chart: ^0.65.0
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # File Handling
  file_picker: ^6.1.1
  open_file: ^3.3.2
  
  # Biometrics
  local_auth: ^2.1.7
  
  # Network
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.9
  
  # Testing
  mockito: ^5.4.2
  test: ^1.24.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
